name: Deploy to okteto
on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
    - LICENSE

    tags:
    - v*

  pull_request:
    paths-ignore: 
    - README.md
    - LICENSE
  schedule:
  - cron: '0 0/12 * * ?'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: |
        if [ -f docker-compose.test.yml ]; then
          docker-compose --file docker-compose.test.yml build
          docker-compose --file docker-compose.test.yml run sut
        else
          docker build . --file Dockerfile
        fi
  deploy:
    needs: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login
      uses: okteto/login@main
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        
    - name: Activate namespace
      uses: okteto/namespace@main
      with:
        namespace: ${{ secrets.OKTETO_NAMESPACE }}
    
    - name: Prepare env
      id: prepare-env
      run: |
        repository="${{github.repository}}"
        arr=(${repository//// })
        IMAGE_NAME=${arr[1]}
        
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
      
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        # Use Docker `latest` tag convention
        [ "$VERSION" == "main" ] && VERSION=latest
        
        echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV
        echo "IMAGE_VERSION=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Build & Push image
      uses: okteto/build@main
      with:
        tag: ${{ steps.prepare-env.outputs.IMAGE_NAME }}:${{ steps.prepare-env.outputs.IMAGE_VERSION }}

    - name: Generate k8s configuration
      run: |
        cat>k8s.yml<<END_TEXT
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: $IMAGE_NAME
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: $IMAGE_NAME
          template:
            metadata:
              labels:
                app: $IMAGE_NAME
            spec:
              containers:
              - image: $IMAGE_NAME:$IMAGE_VERSION
                name: $IMAGE_NAME
                ports:
                - containerPort: 25500
                  protocol: "TCP"
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: $IMAGE_NAME
          annotations:
            dev.okteto.com/auto-ingress: "true"
        spec:
          type: ClusterIP
          ports:
          - name: http
            port: 8080
            protocol: TCP
            targetPort: 25500
          selector:
            app: $IMAGE_NAME
        END_TEXT
    
    - name: Deploy
      uses: okteto/apply@main
      with:
        manifest: k8s.yml
